Traceback (most recent call last):
  File "E:\repo\carrasquel\debugging-with-python\error_example.py", line 14, in <module>
    main()
  File "E:\repo\carrasquel\debugging-with-python\error_example.py", line 10, in main
    spam()
  File "E:\repo\carrasquel\debugging-with-python\error_example.py", line 4, in spam
    bacon()
  File "E:\repo\carrasquel\debugging-with-python\error_example.py", line 7, in bacon
    raise Exception("This is the error message.")
Exception: This is the error message.
